# Generated by Django 3.2.22 on 2023-11-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='enable_sale_time_range',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='sale_time_start',
        ),
        migrations.AddField(
            model_name='goods',
            name='discount_price',
            field=models.PositiveIntegerField(default=1, verbose_name='商品折扣价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='discount_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='折扣时间'),
        ),
        migrations.AddField(
            model_name='goods',
            name='original_price',
            field=models.PositiveIntegerField(default=1, verbose_name='商品原价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='sale_time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='限时时间'),
        ),
    ]
