# Generated by Django 3.2.22 on 2023-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20231103_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['sort', '-id'], 'verbose_name': '商品表', 'verbose_name_plural': '商品表'},
        ),
        migrations.AddField(
            model_name='goods',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
