# Generated by Django 3.2.22 on 2023-10-23 10:53

import backend.utils.order_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20231023_1028'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('unit_price', models.IntegerField(default=0, verbose_name='单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('total_price', models.IntegerField(default=0, verbose_name='总价')),
                ('order_id', models.CharField(default=backend.utils.order_utils.get_goods_order_id, max_length=150, verbose_name='订单号')),
                ('express_name', models.CharField(default='', max_length=150, verbose_name='收货人')),
                ('express_phone', models.CharField(default='', max_length=150, verbose_name='收货手机号码')),
                ('express_area', models.CharField(default='', max_length=150, verbose_name='所在地区')),
                ('express_address', models.CharField(default='', max_length=150, verbose_name='详细地址')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'cmp_order',
            },
        ),
    ]
