# Generated by Django 3.2.22 on 2023-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='订单状态'),
        ),
    ]
