# Generated by Django 3.2.22 on 2023-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': '订单表', 'verbose_name_plural': '订单表'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待发货'), (2, '已发货'), (3, '运送中'), (4, '已签收')], default=1, verbose_name='订单状态'),
        ),
    ]
