# Generated by Django 3.2.22 on 2023-10-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.BigIntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='usercreditslog',
            name='order_id',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='订单号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercreditslog',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='openapi.openapp', verbose_name='应用'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usercreditslog',
            constraint=models.UniqueConstraint(fields=('order_id', 'app'), name='order_id_app'),
        ),
    ]
