# Generated by Django 3.2.22 on 2023-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20231020_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='express_address',
            field=models.CharField(default='', max_length=150, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='user',
            name='express_area',
            field=models.CharField(default='', max_length=150, verbose_name='所在地区'),
        ),
        migrations.AddField(
            model_name='user',
            name='express_name',
            field=models.CharField(default='', max_length=150, verbose_name='收货人'),
        ),
        migrations.AddField(
            model_name='user',
            name='express_phone',
            field=models.CharField(default='', max_length=150, verbose_name='收货手机号码'),
        ),
    ]
