# Generated by Django 3.2.22 on 2023-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20231103_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weiyi_access_token_expire_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='唯艺 access token 过期时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weiyi_access_token',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='唯艺 access token'),
        ),
    ]
