# Generated by Django 3.2.22 on 2023-11-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20231103_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='weiyi_access_token',
            new_name='weiyi_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='weiyi_access_token_expire_at',
            new_name='weiyi_token_expire_at',
        ),
    ]
