# Generated by Django 3.2.22 on 2023-11-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20231108_1736'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercreditslog',
            name='order_id_app',
        ),
        migrations.AddField(
            model_name='weiyitreasure',
            name='cover',
            field=models.CharField(default='', max_length=150, verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weiyitreasure',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='商品名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weiyitreasure',
            name='number',
            field=models.IntegerField(default=1, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weiyitreasure',
            name='type_market',
            field=models.IntegerField(choices=[(1, '版权品'), (2, '衍生品'), (3, '数字身份')], default=1, verbose_name='市场类型'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='weiyitreasure',
            index_together={('name', 'number')},
        ),
        migrations.AddConstraint(
            model_name='usercreditslog',
            constraint=models.UniqueConstraint(fields=('order_id', 'app'), name='user_credits_log_order_id_app'),
        ),
        migrations.AddConstraint(
            model_name='weiyitreasure',
            constraint=models.UniqueConstraint(fields=('name', 'number'), name='weiyi_treasure_name_number'),
        ),
    ]
