# Generated by Django 3.2.22 on 2023-11-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20231109_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='weiyitreasure',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
