# Generated by Django 3.2.22 on 2023-11-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_weiyitreasure_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeiyiTreasure',
            new_name='UserWeiyiTreasure',
        ),
        migrations.AlterModelTable(
            name='userweiyitreasure',
            table='cmp_user_weiyi_treasure',
        ),
    ]
