# Generated by Django 3.2.22 on 2023-11-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20231109_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiyiTreasureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_uuid', models.CharField(max_length=150, unique=True, verbose_name='商品唯一标识')),
                ('name', models.CharField(max_length=150, verbose_name='商品名')),
                ('is_gold', models.BooleanField(default=False, verbose_name='是否是金卡')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='价格')),
            ],
            options={
                'verbose_name': '唯艺藏品信息表',
                'verbose_name_plural': '唯艺藏品信息表',
                'db_table': 'cmp_weiyi_treasure_info',
            },
        ),
        migrations.AlterModelOptions(
            name='userweiyitreasure',
            options={'verbose_name': '用户唯艺藏品表', 'verbose_name_plural': '用户唯艺藏品表'},
        ),
    ]
