# Generated by Django 3.2.22 on 2023-11-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_weiyitreasureinfo_is_white_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weiyitreasureinfo',
            old_name='is_white_list',
            new_name='is_whitelist',
        ),
    ]
