# Generated by Django 3.2.22 on 2023-11-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_is_white_list_weiyitreasureinfo_is_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweiyitreasure',
            name='is_rebate',
            field=models.BooleanField(default=False, verbose_name='是否已经返利'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='邀请人'),
        ),
    ]
