# Generated by Django 3.2.22 on 2023-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20231109_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercreditslog',
            options={'ordering': ['-id'], 'verbose_name': '用户积分记录', 'verbose_name_plural': '用户积分记录'},
        ),
        migrations.AlterField(
            model_name='user',
            name='express_address',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='express_area',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='所在地区'),
        ),
        migrations.AlterField(
            model_name='user',
            name='express_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='user',
            name='express_phone',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='收货手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weiyi_token',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='唯艺登录状态'),
        ),
    ]
