# Generated by Django 3.2.22 on 2023-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=150, verbose_name='应用名称')),
                ('app_id', models.CharField(max_length=150, unique=True, verbose_name='应用ID')),
                ('app_secret', models.CharField(max_length=150, verbose_name='应用密钥')),
            ],
            options={
                'verbose_name': '开放应用表',
                'verbose_name_plural': '开放应用表',
                'db_table': 'cmp_openapi_app',
            },
        ),
    ]
