# Generated by Django 3.2.22 on 2023-10-20 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='权限标识')),
                ('name', models.CharField(max_length=255, verbose_name='权限名称')),
                ('description', models.CharField(default='', max_length=255, verbose_name='权限描述')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 'cmp_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='角色名称')),
                ('description', models.CharField(default='', max_length=255, verbose_name='角色描述')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'cmp_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.adminpermission', verbose_name='权限')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限表',
                'verbose_name_plural': '角色权限表',
                'db_table': 'cmp_role_permission',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(through='back.RolePermission', to='back.AdminPermission', verbose_name='权限'),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('nickname', models.CharField(max_length=20, verbose_name='显示名称')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='帐号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('avatar', models.CharField(default='http://43.137.46.100/media/default_avatar.svg', max_length=255, verbose_name='头像')),
                ('summary', models.CharField(default='', max_length=512, verbose_name='简介')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='是否超级管理员')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '后台用户表',
                'verbose_name_plural': '后台用户表',
                'db_table': 'cmp_admin_user',
            },
        ),
    ]
