# Generated by Django 4.2.6 on 2023-10-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='avatar',
            field=models.CharField(default='http://mall.gamefi01.art/media/default_avatar.svg', max_length=255, verbose_name='头像'),
        ),
    ]
