# Generated by Django 3.2.22 on 2023-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_adminuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='avatar',
            field=models.CharField(default='https://mall.gamefi01.art/media/default_avatar.svg', max_length=255, verbose_name='头像'),
        ),
    ]
